### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheCableGuy99** [remvze/timesy#1]
Hi,

Can I request 2 things please?

1) The ability to enter times much longer than 12 hours? Such as days, weeks, years?
2) The ability to enter the event time so it automatically works out how long is left? (Might have to add timezone in our docker_compose but easy enough).

Thanks for your consideration.

**Comment by remvze** [comment]
Hey there. Sorry for responding late; I was extremely busy. As for your requests, I will increase the hours to 24 or 48. Longer than that doesn't make much sense since the timers stop when the tab is closed, and no one keeps a tab open for a year. The second suggestion is out of the scope of this project.
